project:
  type: website
  output-dir: docs

website:
  title: "Michael Gethers"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts/index.qmd
        text: Writing
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true